import { Store } from "../components/types/store.types";

export const stores: Store[] = [
  {
    id: 0,
    name: "Store Mumbai 1",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    address: "Andheri West",
  },
  {
    id: 1,
    name: "Store Ghazipur 1",
    city: "Ghazipur",
    state: "Uttar Pradesh",
    lat: 25.5833,
    lng: 83.5853,
    address: "Ghazipur, Uttar Pradesh, India",
  },
  {
    id: 2,
    name: "Store Mumbai 2",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.1,
    lng: 72.88,
    address: "Bandra",
  },
  {
    id: 3,
    name: "Store Mumbai 3",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.09,
    lng: 72.87,
    address: "Juhu",
  },
  {
    id: 4,
    name: "Store Pune 1",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    address: "Koregaon Park",
  },
  {
    id: 5,
    name: "Store Pune 2",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.53,
    lng: 73.85,
    address: "Viman Nagar",
  },
  {
    id: 6,
    name: "Store Delhi 1",
    city: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    address: "Connaught Place",
  },
  {
    id: 7,
    name: "Store Delhi 2",
    city: "Delhi",
    state: "Delhi",
    lat: 28.61,
    lng: 77.21,
    address: "Karol Bagh",
  },
  {
    id: 8,
    name: "Store Delhi 3",
    city: "Delhi",
    state: "Delhi",
    lat: 28.63,
    lng: 77.22,
    address: "Saket",
  },
  {
    id: 9,
    name: "Store Bangalore 1",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    address: "MG Road",
  },
  {
    id: 10,
    name: "Store Bangalore 2",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.97,
    lng: 77.59,
    address: "Koramangala",
  },
  {
    id: 11,
    name: "Store Bangalore 3",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.98,
    lng: 77.6,
    address: "Indiranagar",
  },
  {
    id: 15,
    name: "Store Chennai 1",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    address: "T. Nagar",
  },
  {
    id: 16,
    name: "Store Chennai 2",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    address: "Adyar",
  },
  {
    id: 17,
    name: "Store Chennai 3",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.09,
    lng: 80.26,
    address: "Velachery",
  },
  {
    id: 21,
    name: "Store Jaipur 1",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    address: "MI Road",
  },
  {
    id: 22,
    name: "Store Jaipur 2",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.78,
    address: "C-Scheme",
  },
  {
    id: 23,
    name: "Store Jaipur 3",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.79,
    address: "Bani Park",
  },
  {
    id: 24,
    name: "Store Lucknow 1",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8467,
    lng: 80.9462,
    address: "Gomti Nagar",
  },
  {
    id: 25,
    name: "Store Lucknow 2",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.85,
    lng: 80.95,
    address: "Hazratganj",
  },
  {
    id: 26,
    name: "Store Lucknow 3",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.84,
    lng: 80.94,
    address: "Alambagh",
  },
  {
    id: 27,
    name: "Store Ahmedabad 1",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    address: "CG Road",
  },
  {
    id: 28,
    name: "Store Ahmedabad 2",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.02,
    lng: 72.57,
    address: "Navrangpura",
  },
  {
    id: 29,
    name: "Store Ahmedabad 3",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.03,
    lng: 72.58,
    address: "Satellite",
  },
  {
    id: 30,
    name: "Store Kochi 1",
    city: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    address: "MG Road",
  },
  {
    id: 31,
    name: "Store Kochi 2",
    city: "Kochi",
    state: "Kerala",
    lat: 9.93,
    lng: 76.27,
    address: "Marine Drive",
  },
  {
    id: 32,
    name: "Store Kochi 3",
    city: "Kochi",
    state: "Kerala",
    lat: 9.94,
    lng: 76.26,
    address: "Vyttila",
  },
  {
    id: 33,
    name: "Store Surat 1",
    city: "Surat",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
    address: "Varachha",
  },
  {
    id: 38,
    name: "Store Patna 1",
    city: "Patna",
    state: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    address: "Boring Road",
  },
  {
    id: 39,
    name: "Store Patna 2",
    city: "Patna",
    state: "Bihar",
    lat: 25.59,
    lng: 85.13,
    address: "Kankarbagh",
  },
  {
    id: 48,
    name: "Store Vadodara 1",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3072,
    lng: 73.1812,
    address: "Alkapuri",
  },
  {
    id: 49,
    name: "Store Vadodara 2",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3,
    lng: 73.18,
    address: "Manjalpur",
  },
  {
    id: 50,
    name: "Store Nashik 1",
    city: "Nashik",
    state: "Maharashtra",
    lat: 19.9975,
    lng: 73.7898,
    address: "College Road",
  },
];