import { Store } from "../components/types/store.types";

export const stores: Store[] = [
  {
    id: 1,
    name: "Store Mumbai 1",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    address: "Andheri West",
  },
  {
    id: 2,
    name: "Store Mumbai 2",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.1,
    lng: 72.88,
    address: "Bandra",
  },
  {
    id: 3,
    name: "Store Mumbai 3",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.09,
    lng: 72.87,
    address: "Juhu",
  },
  {
    id: 4,
    name: "Store Pune 1",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    address: "Koregaon Park",
  },
  {
    id: 5,
    name: "Store Pune 2",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.53,
    lng: 73.85,
    address: "Viman Nagar",
  },
  {
    id: 6,
    name: "Store Delhi 1",
    city: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    address: "Connaught Place",
  },
  {
    id: 7,
    name: "Store Delhi 2",
    city: "Delhi",
    state: "Delhi",
    lat: 28.61,
    lng: 77.21,
    address: "Karol Bagh",
  },
  {
    id: 8,
    name: "Store Delhi 3",
    city: "Delhi",
    state: "Delhi",
    lat: 28.63,
    lng: 77.22,
    address: "Saket",
  },
  {
    id: 9,
    name: "Store Bangalore 1",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    address: "MG Road",
  },
  {
    id: 10,
    name: "Store Bangalore 2",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.97,
    lng: 77.59,
    address: "Koramangala",
  },
  {
    id: 11,
    name: "Store Bangalore 3",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.98,
    lng: 77.6,
    address: "Indiranagar",
  },
  {
    id: 12,
    name: "Store Hyderabad 1",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lng: 78.4867,
    address: "Banjara Hills",
  },
  {
    id: 13,
    name: "Store Hyderabad 2",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.39,
    lng: 78.48,
    address: "Hitech City",
  },
  {
    id: 14,
    name: "Store Hyderabad 3",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.38,
    lng: 78.48,
    address: "Gachibowli",
  },
  {
    id: 15,
    name: "Store Chennai 1",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    address: "T. Nagar",
  },
  {
    id: 16,
    name: "Store Chennai 2",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    address: "Adyar",
  },
  {
    id: 17,
    name: "Store Chennai 3",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.09,
    lng: 80.26,
    address: "Velachery",
  },
  {
    id: 18,
    name: "Store Kolkata 1",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    address: "Salt Lake",
  },
  {
    id: 19,
    name: "Store Kolkata 2",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.36,
    address: "Park Street",
  },
  {
    id: 20,
    name: "Store Kolkata 3",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.37,
    address: "New Town",
  },
  {
    id: 21,
    name: "Store Jaipur 1",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    address: "MI Road",
  },
  {
    id: 22,
    name: "Store Jaipur 2",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.78,
    address: "C-Scheme",
  },
  {
    id: 23,
    name: "Store Jaipur 3",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.79,
    address: "Bani Park",
  },
  {
    id: 24,
    name: "Store Lucknow 1",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8467,
    lng: 80.9462,
    address: "Gomti Nagar",
  },
  {
    id: 25,
    name: "Store Lucknow 2",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.85,
    lng: 80.95,
    address: "Hazratganj",
  },
  {
    id: 26,
    name: "Store Lucknow 3",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.84,
    lng: 80.94,
    address: "Alambagh",
  },
  {
    id: 27,
    name: "Store Ahmedabad 1",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    address: "CG Road",
  },
  {
    id: 28,
    name: "Store Ahmedabad 2",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.02,
    lng: 72.57,
    address: "Navrangpura",
  },
  {
    id: 29,
    name: "Store Ahmedabad 3",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.03,
    lng: 72.58,
    address: "Satellite",
  },
  {
    id: 30,
    name: "Store Kochi 1",
    city: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    address: "MG Road",
  },
  {
    id: 31,
    name: "Store Kochi 2",
    city: "Kochi",
    state: "Kerala",
    lat: 9.93,
    lng: 76.27,
    address: "Marine Drive",
  },
  {
    id: 32,
    name: "Store Kochi 3",
    city: "Kochi",
    state: "Kerala",
    lat: 9.94,
    lng: 76.26,
    address: "Vyttila",
  },
  {
    id: 33,
    name: "Store Surat 1",
    city: "Surat",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
    address: "Varachha",
  },
  {
    id: 34,
    name: "Store Surat 2",
    city: "Surat",
    state: "Gujarat",
    lat: 21.17,
    lng: 72.83,
    address: "Adajan",
  },
  {
    id: 35,
    name: "Store Surat 3",
    city: "Surat",
    state: "Gujarat",
    lat: 21.16,
    lng: 72.83,
    address: "Pal",
  },
  {
    id: 36,
    name: "Store Indore 1",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.7196,
    lng: 75.8577,
    address: "MG Road",
  },
  {
    id: 37,
    name: "Store Indore 2",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.72,
    lng: 75.85,
    address: "Vijay Nagar",
  },
  {
    id: 38,
    name: "Store Patna 1",
    city: "Patna",
    state: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    address: "Boring Road",
  },
  {
    id: 39,
    name: "Store Patna 2",
    city: "Patna",
    state: "Bihar",
    lat: 25.59,
    lng: 85.13,
    address: "Kankarbagh",
  },
  {
    id: 40,
    name: "Store Guwahati 1",
    city: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    address: "Pan Bazaar",
  },
  {
    id: 41,
    name: "Store Guwahati 2",
    city: "Guwahati",
    state: "Assam",
    lat: 26.14,
    lng: 91.73,
    address: "Paltan Bazaar",
  },
  {
    id: 42,
    name: "Store Bhopal 1",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    address: "MP Nagar",
  },
  {
    id: 43,
    name: "Store Bhopal 2",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.26,
    lng: 77.41,
    address: "Kolar Road",
  },
  {
    id: 44,
    name: "Store Trivandrum 1",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    address: "MG Road",
  },
  {
    id: 45,
    name: "Store Trivandrum 2",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.52,
    lng: 76.93,
    address: "Vazhuthacaud",
  },
  {
    id: 46,
    name: "Store Ranchi 1",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.3441,
    lng: 85.3096,
    address: "Harmu Road",
  },
  {
    id: 47,
    name: "Store Ranchi 2",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.34,
    lng: 85.3,
    address: "Kantatoli",
  },
  {
    id: 48,
    name: "Store Vadodara 1",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3072,
    lng: 73.1812,
    address: "Alkapuri",
  },
  {
    id: 49,
    name: "Store Vadodara 2",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3,
    lng: 73.18,
    address: "Manjalpur",
  },
  {
    id: 50,
    name: "Store Nashik 1",
    city: "Nashik",
    state: "Maharashtra",
    lat: 19.9975,
    lng: 73.7898,
    address: "College Road",
  },
];