import { Bikee, OverlayBike, Store } from "@/types";
import { Calendar, Clock,Truck,Bike } from "lucide-react";

export const stories = [
  {
    title: "Manali Tours",
    excerpt:
      "We visited Warren on his home trails in Santa Cruz, California, and caught up with what he has been up to lately.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/aAj43fIqRLdaBheS_WarrenKniss_CrankCase_Web-6.jpg?auto=format,compress&rect=0,159,2048,1366&w=1280&h=854",
    link: "#",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
  },
  {
    title: "Spiti Tours",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/Z1IBYZbqstJ98Fqh_Jake-Gasaway_bike_craigburn-7.jpg?auto=format%2Ccompress&rect=2%2C0%2C4768%2C3181&w=1280&h=854",
    link: "#",
    className: "absolute top-25 left-[25%] rotate-[-7deg]",
  },
  {
    title: "Manali Tours",
    excerpt:
      "Sarah shares her incredible experience from the trails of British Columbia.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/Z1IBYZbqstJ98Fqh_Jake-Gasaway_bike_craigburn-7.jpg?auto=format%2Ccompress&rect=2%2C0%2C4768%2C3181&w=1280&h=854",
    link: "#",
    className: "absolute top-5 left-[40%] rotate-[8deg]",
  },
  {
    title: "Shimla Tours",
    excerpt:
      "Follow the adrenaline-packed journey of our riders through the toughest enduro races.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/Zw7GAYF3NbkBXejN_20241009_Powers_RedbullRampage-Day3_1397.jpg?auto=format,compress&rect=0%2C0%2C2999%2C2001&w=1280&h=854",
    link: "#",
    className: "absolute top-15 right-[10%] rotate-[10deg]",
  },
  {
    title: "Manali Tours",
    excerpt:
      "A behind-the-scenes look at what goes into creating the perfect trail machine.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/ZxGHOYF3NbkBXsYZ_rampage-24_2017.jpg?auto=format,compress&rect=0%2C0%2C2879%2C1921&w=1280&h=854",
    link: "#",
    className: "absolute top-20 left-[35%] rotate-[2deg]",
  },
  {
    title: "Shimla Tours",
    excerpt:
      "An adventure of a lifetime: riding through the stunning landscapes of Patagonia.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/ZzI-m68jQArT0tOx_Riding_2021_05_04_Smartwool_salida_mtb_IF-7980.jpg?auto=format%2Ccompress&rect=1%2C0%2C2878%2C1920&w=1280&h=854",
    link: "#",
    className: "absolute top-25 right-[25%] rotate-[-7deg]",
  },
  {
    title: "Manali Tours",
    excerpt:
      "From rigid frames to modern marvels – the journey of MTB technology.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/Zxf9PYF3NbkBX3vv_A94A2229.jpg?auto=format%2Ccompress&rect=1%2C0%2C2878%2C1920&w=1280&h=854",
    link: "#",
    className: "absolute top-8 left-[30%] rotate-[4deg]",
  },
  {
    title: "Shimla Tours",
    excerpt:
      "Tom takes us on a deep dive into some of the most scenic trails across Europe.",
    img: "https://yeticycles-prod.zaneray.com/cms/images/ZsYP8UaF0TcGJLbJ_SturdyDirtyRTR2024-133.jpg?auto=format%2Ccompress&rect=0%2C0%2C2047%2C1366&w=1280&h=854",
    link: "#",
    className: "absolute top-40 right-[20%] rotate-[6deg]",
  },
];


export const bikes: Bikee[] = [
  {
    id: "serow",
    name: "SEROW",
    logo: "/images/serow-logo.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 9,
      braking: 7,
      frame: 9,
      tire: 8,
      weight: 9,
      comfort: 7,
    },
    description: [
      "High suspension",
      "Balanced braking power",
      "Lightweight",
      "Strong frame durability",
    ],
  },
  {
    id: "saola",
    name: "SAOLA",
    logo: "/images/saola-logo.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 7,
      braking: 8,
      frame: 7,
      tire: 6,
      weight: 8,
      comfort: 6,
    },
    description: [
      "Efficient climbing",
      "Responsive braking",
      "Comfortable ride",
      "Good weight balance",
    ],
  },
  {
    id: "takin",
    name: "TAKIN",
    logo: "/images/takin-logo.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 8,
      braking: 9,
      frame: 8,
      tire: 7,
      weight: 7,
      comfort: 8,
    },
    description: [
      "Excellent control",
      "Durable build",
      "Powerful braking",
      "All-terrain grip",
    ],
  },
];

export const overlayBikes: OverlayBike[] = [
  {
    id: "serow",
    name: "Serow-1",
    logo: "/images/serow-logo.png",
    image: "/images/serow-big-img.png",
    details: {
      size: "M, L, XL",
      color: "Forest Green",
      dimension: "29” Wheels, 1200mm wheelbase",
      material: "Carbon Fiber Frame",
    },
    skus: [
      {
        id: "serow-sku1",
        name: "Serow Trail",
        image: "/images/serow-big-img.png",
      },
      {
        id: "serow-sku2",
        name: "Serow XC",
        image: "/images/saola-big-img.png",
      },
      {
        id: "serow-sku3",
        name: "Serow Enduro",
        image: "/images/takin-big-img.png",
      },
    ],
  },
  {
    id: "saola",
    name: "Saola-2",
    logo: "/images/saola-logo.png",
    image: "/images/saola-big-img.png",
    details: {
      size: "S, M, L",
      color: "Matte Black",
      dimension: "27.5” Wheels, 1150mm wheelbase",
      material: "Aluminum Alloy",
    },
    skus: [
      {
        id: "saola-sku1",
        name: "Saola Pro",
        image: "/images/serow-big-img.png",
      },
      {
        id: "saola-sku2",
        name: "Saola Comp",
        image: "/images/saola-big-img.png",
      },
      {
        id: "saola-sku3",
        name: "Saola Elite",
        image: "/images/takin-big-img.png",
      },
    ],
  },
  {
    id: "takin",
    name: "Takin-3",
    logo: "/images/takin-logo.png",
    image: "/images/takin-big-img.png",
    details: {
      size: "L, XL",
      color: "Crimson Red",
      dimension: "29” Wheels, 1250mm wheelbase",
      material: "Steel Hardtail",
    },
    skus: [
      {
        id: "takin-sku1",
        name: "Takin Downhill",
        image: "/images/serow-big-img.png",
      },
      {
        id: "takin-sku2",
        name: "Takin Freeride",
        image: "/images/saola-big-img.png",
      },
      {
        id: "takin-sku3",
        name: "Takin All-Mountain",
        image: "/images/takin-big-img.png",
      },
    ],
  },
];

export const ourProducts = [
  {
    id: "bikes",
    title: "BIKES",
    image:
      "https://wallpapers.com/images/featured/mountain-bike-nscgkm2azbwgg2py.jpg",
    link: "/bikes",
  },
  {
    id: "apparel",
    title: "APPAREL",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrhQa7z0X9GcmaJkfEkzkmjmayEOdkoudJyg&s",
    link: "/apparel",
  },
  {
    id: "accessories",
    title: "ACCESSORIES",
    image:
      "https://png.pngtree.com/thumb_back/fh260/background/20240401/pngtree-bicycle-spare-parts-and-accessories-image_15648878.jpg",
    link: "/accessories",
  },
];

export const steps = [
  {
    title: "Book a Test ride",
    desc: "Choose your preferred cycle model and book a test ride with just a few simple steps.",
    icon: Bike,
  },
  {
    title: "Select a date and timeslot",
    desc: "Pick a convenient date and time that fits your schedule for the test ride.",
    icon: Calendar,
  },
  {
    title: "Rider reaches you",
    desc: "Our expert rider will arrive at your location with the cycle, ready to guide you.",
    icon: Truck,
  },
  {
    title: "Do the test drive",
    desc: "Experience the ride first-hand, explore features, and feel the freedom on wheels.",
    icon: Clock,
  },
];

export const bikesData = [
  {
    name: "Serow",
    logo: "/images/serow-logo.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Internal Cable", value: "Routing" },
      { label: "Mechanical Suspension", value: "Suspension Fork" },
      { label: "Mechanical Disc", value: "Brake" },
    ],
    specs: {
      frameset: "RADFlex Alloy – Internal Cable Routing, 17.5”, Boost – 148MM",
      suspension: "SR Suntour X1 Boost Air, 120MM, Hydraulic Lockout",
      braking: "Shimano MT200 Hydraulic Disc Brakes – 160MM",
    },
    colors: {
      gradient: "#C6B783, #806D2A", // top → bottom
      cta: "#C6B783",
    },
  },
  {
    name: "Saola",
    logo: "/images/saola-logo.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Hydraulic Brake", value: "Disc Brake" },
      { label: "Full Suspension", value: "Suspension" },
      { label: "Carbon Material", value: "Frame" },
    ],
    specs: {
      frameset: "Carbon Alloy – Internal Cable Routing, 18”",
      suspension: "FOX Float, 130MM, Hydraulic Lockout",
      braking: "Shimano XT Hydraulic Disc Brakes – 180MM",
    },
     colors: {
      gradient: "#0046D7, #FFFFFF",
      cta: "#0046D7",
    },
  },
  {
    name: "Takin",
    logo: "/images/takin-logo.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Internal Cable", value: "Routing" },
      { label: "Mechanical Suspension", value: "Suspension Fork" },
      { label: "Mechanical Disc", value: "Brake" },
    ],
    specs: {
      frameset: "Aluminum Alloy – Internal Cable Routing, 17”",
      suspension: "RockShox Judy, 120MM, Hydraulic Lockout",
      braking: "Shimano MT400 Hydraulic Disc Brakes – 160MM",
    },
    colors: {
      gradient: "#516316, #F1FFC3",
      cta: "#516316",
    },
  },
];

export const stores: Store[] = [
  {
    id: 1,
    name: "Store Mumbai 1",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    address: "Andheri West",
  },
  {
    id: 2,
    name: "Store Mumbai 2",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.1,
    lng: 72.88,
    address: "Bandra",
  },
  {
    id: 3,
    name: "Store Mumbai 3",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.09,
    lng: 72.87,
    address: "Juhu",
  },
  {
    id: 4,
    name: "Store Pune 1",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    address: "Koregaon Park",
  },
  {
    id: 5,
    name: "Store Pune 2",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.53,
    lng: 73.85,
    address: "Viman Nagar",
  },
  {
    id: 6,
    name: "Store Delhi 1",
    city: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    address: "Connaught Place",
  },
  {
    id: 7,
    name: "Store Delhi 2",
    city: "Delhi",
    state: "Delhi",
    lat: 28.61,
    lng: 77.21,
    address: "Karol Bagh",
  },
  {
    id: 8,
    name: "Store Delhi 3",
    city: "Delhi",
    state: "Delhi",
    lat: 28.63,
    lng: 77.22,
    address: "Saket",
  },
  {
    id: 9,
    name: "Store Bangalore 1",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    address: "MG Road",
  },
  {
    id: 10,
    name: "Store Bangalore 2",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.97,
    lng: 77.59,
    address: "Koramangala",
  },
  {
    id: 11,
    name: "Store Bangalore 3",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.98,
    lng: 77.6,
    address: "Indiranagar",
  },
  {
    id: 12,
    name: "Store Hyderabad 1",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lng: 78.4867,
    address: "Banjara Hills",
  },
  {
    id: 13,
    name: "Store Hyderabad 2",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.39,
    lng: 78.48,
    address: "Hitech City",
  },
  {
    id: 14,
    name: "Store Hyderabad 3",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.38,
    lng: 78.48,
    address: "Gachibowli",
  },
  {
    id: 15,
    name: "Store Chennai 1",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    address: "T. Nagar",
  },
  {
    id: 16,
    name: "Store Chennai 2",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    address: "Adyar",
  },
  {
    id: 17,
    name: "Store Chennai 3",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.09,
    lng: 80.26,
    address: "Velachery",
  },
  {
    id: 18,
    name: "Store Kolkata 1",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    address: "Salt Lake",
  },
  {
    id: 19,
    name: "Store Kolkata 2",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.36,
    address: "Park Street",
  },
  {
    id: 20,
    name: "Store Kolkata 3",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.37,
    address: "New Town",
  },
  {
    id: 21,
    name: "Store Jaipur 1",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    address: "MI Road",
  },
  {
    id: 22,
    name: "Store Jaipur 2",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.78,
    address: "C-Scheme",
  },
  {
    id: 23,
    name: "Store Jaipur 3",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.79,
    address: "Bani Park",
  },
  {
    id: 24,
    name: "Store Lucknow 1",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8467,
    lng: 80.9462,
    address: "Gomti Nagar",
  },
  {
    id: 25,
    name: "Store Lucknow 2",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.85,
    lng: 80.95,
    address: "Hazratganj",
  },
  {
    id: 26,
    name: "Store Lucknow 3",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.84,
    lng: 80.94,
    address: "Alambagh",
  },
  {
    id: 27,
    name: "Store Ahmedabad 1",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    address: "CG Road",
  },
  {
    id: 28,
    name: "Store Ahmedabad 2",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.02,
    lng: 72.57,
    address: "Navrangpura",
  },
  {
    id: 29,
    name: "Store Ahmedabad 3",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.03,
    lng: 72.58,
    address: "Satellite",
  },
  {
    id: 30,
    name: "Store Kochi 1",
    city: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    address: "MG Road",
  },
  {
    id: 31,
    name: "Store Kochi 2",
    city: "Kochi",
    state: "Kerala",
    lat: 9.93,
    lng: 76.27,
    address: "Marine Drive",
  },
  {
    id: 32,
    name: "Store Kochi 3",
    city: "Kochi",
    state: "Kerala",
    lat: 9.94,
    lng: 76.26,
    address: "Vyttila",
  },
  {
    id: 33,
    name: "Store Surat 1",
    city: "Surat",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
    address: "Varachha",
  },
  {
    id: 34,
    name: "Store Surat 2",
    city: "Surat",
    state: "Gujarat",
    lat: 21.17,
    lng: 72.83,
    address: "Adajan",
  },
  {
    id: 35,
    name: "Store Surat 3",
    city: "Surat",
    state: "Gujarat",
    lat: 21.16,
    lng: 72.83,
    address: "Pal",
  },
  {
    id: 36,
    name: "Store Indore 1",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.7196,
    lng: 75.8577,
    address: "MG Road",
  },
  {
    id: 37,
    name: "Store Indore 2",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.72,
    lng: 75.85,
    address: "Vijay Nagar",
  },
  {
    id: 38,
    name: "Store Patna 1",
    city: "Patna",
    state: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    address: "Boring Road",
  },
  {
    id: 39,
    name: "Store Patna 2",
    city: "Patna",
    state: "Bihar",
    lat: 25.59,
    lng: 85.13,
    address: "Kankarbagh",
  },
  {
    id: 40,
    name: "Store Guwahati 1",
    city: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    address: "Pan Bazaar",
  },
  {
    id: 41,
    name: "Store Guwahati 2",
    city: "Guwahati",
    state: "Assam",
    lat: 26.14,
    lng: 91.73,
    address: "Paltan Bazaar",
  },
  {
    id: 42,
    name: "Store Bhopal 1",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    address: "MP Nagar",
  },
  {
    id: 43,
    name: "Store Bhopal 2",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.26,
    lng: 77.41,
    address: "Kolar Road",
  },
  {
    id: 44,
    name: "Store Trivandrum 1",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    address: "MG Road",
  },
  {
    id: 45,
    name: "Store Trivandrum 2",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.52,
    lng: 76.93,
    address: "Vazhuthacaud",
  },
  {
    id: 46,
    name: "Store Ranchi 1",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.3441,
    lng: 85.3096,
    address: "Harmu Road",
  },
  {
    id: 47,
    name: "Store Ranchi 2",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.34,
    lng: 85.3,
    address: "Kantatoli",
  },
  {
    id: 48,
    name: "Store Vadodara 1",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3072,
    lng: 73.1812,
    address: "Alkapuri",
  },
  {
    id: 49,
    name: "Store Vadodara 2",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3,
    lng: 73.18,
    address: "Manjalpur",
  },
  {
    id: 50,
    name: "Store Nashik 1",
    city: "Nashik",
    state: "Maharashtra",
    lat: 19.9975,
    lng: 73.7898,
    address: "College Road",
  },
];
