import { Bikee, OverlayBike, Store } from "@/types";
import { Calendar, Clock, Truck, Bike } from "lucide-react";

export const stories = [
  {
    id: 1,
    title: "Manali Adventures",
    date: "20 September 2025",
    excerpt:
      "We visited Warren on his home trails in Santa Cruz, California, and caught up with what he has been up to lately.",
    img: "/images/manali.jpg",
    link: "#",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Sunrise Trekking",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Alice Johnson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Rafting Fun",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Bob Smith",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Adventure",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Carla Williams",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Camping Under Stars",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "David Lee",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Emma Brown",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Wildlife Spotting",
        user_experience:
          "Saw some rare Himalayan birds. Felt very connected to nature.",
        author: "Frank Garcia",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Bonfire",
        user_experience:
          "The evening bonfire with stories and music was the highlight of the trip.",
        author: "Grace Miller",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Village Visit",
        user_experience:
          "Visiting the local villages gave me insight into traditional life in Manali.",
        author: "Henry Davis",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "Sipping Chai At Spiti",
    date: "23 December 2023",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    img: "/images/sipping.jpg",
    link: "#",
    className: "absolute top-25 left-[25%] rotate-[-7deg]",
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Chai Plantation Walk",
        user_experience:
          "Walking through the tea plantations was serene and calming. The aroma of fresh chai leaves made the whole experience magical.",
        author: "Irene Thomas",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Sunset Viewpoint",
        user_experience:
          "The sunset over Spiti valley is something I will never forget. Colors of the sky reflected on the river created a painting-like scene.",
        author: "Jack Wilson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Homestay Experience",
        user_experience:
          "Staying at a local homestay made me feel at home. The hosts shared their culture and traditional meals with so much warmth.",
        author: "Karen Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "Every corner of Spiti is photogenic! The rugged mountains, winding rivers, and colorful monasteries were perfect for photography.",
        author: "Leo Martinez",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Monastery Visit",
        user_experience:
          "Visiting ancient monasteries gave me a deep insight into local spirituality. The monks were welcoming and explained their rituals patiently.",
        author: "Maya Patel",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Village Interaction",
        user_experience:
          "Talking to the villagers was enlightening. I learned how they cultivate crops in such harsh conditions and their love for community.",
        author: "Nikhil Rao",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Side Chai Break",
        user_experience:
          "Sipping fresh chai beside the river while listening to the flowing water was the most peaceful experience I’ve had in years.",
        author: "Olivia Chen",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Stargazing Night",
        user_experience:
          "The night sky in Spiti is unbelievably clear. Stargazing with a cup of chai made me feel connected to the universe.",
        author: "Pranav Desai",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Kali's Abode, Faridkots Reverence",
    date: "16 March 2021",
    excerpt:
      "Sarah shares her incredible experience from the trails of British Columbia and the spiritual journey in Faridkots.",
    img: "/images/kali.png",
    link: "#",
    className: "absolute top-5 left-[40%] rotate-[8deg]",
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Spiritual Awakening",
        user_experience:
          "Visiting Kali’s Abode felt like a spiritual awakening. The atmosphere is serene and charged with positive energy.",
        author: "Sarah Thompson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Temple Architecture",
        user_experience:
          "The intricate carvings and traditional architecture of the temple left me awestruck. Every detail tells a story.",
        author: "Ravi Kumar",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Meditation Sessions",
        user_experience:
          "Participating in meditation sessions here gave me peace like never before. The guides were knowledgeable and patient.",
        author: "Anita Joshi",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Rituals",
        user_experience:
          "Observing the local rituals was fascinating. I learned so much about Faridkots’ traditions and cultural heritage.",
        author: "Manish Verma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Scenic Trails",
        user_experience:
          "The trails around Kali’s Abode are scenic and peaceful. Every walk felt like a journey into nature’s heart.",
        author: "Priya Sharma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Community Interaction",
        user_experience:
          "Interacting with the local community enriched my experience. Their stories and hospitality were heartwarming.",
        author: "Rahul Mehta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Aarti",
        user_experience:
          "The evening aarti was mesmerizing. The chants, lamps, and devotion created a magical ambiance.",
        author: "Neha Gupta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Nature Walks",
        user_experience:
          "Walking through the surrounding forests and hills was refreshing. The connection with nature was revitalizing.",
        author: "Vikram Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: 4,
    title: "The Seven Hills",
    date: "15 August 2020",
    excerpt:
      "Experience the breathtaking landscapes and vibrant culture across the Seven Hills, capturing adventure, nature, and local traditions.",
    img: "/images/seven-hills.jpg",
    link: "#",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Hilltop Sunrise",
        user_experience:
          "Waking up on the hilltops to witness the sunrise was an unforgettable experience. The sky was painted in vivid colors.",
        author: "Alex Turner",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Forest Trekking",
        user_experience:
          "Trekking through dense forests around the hills brought me close to nature. Birds and wildlife sightings made it magical.",
        author: "Bella Martin",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Village Exploration",
        user_experience:
          "Exploring local villages gave me insight into rural life and traditions. The hospitality of villagers was heartwarming.",
        author: "Charlie Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Waterfall Adventure",
        user_experience:
          "Discovering hidden waterfalls along the trails was thrilling. The cool water and scenic surroundings were perfect for relaxation.",
        author: "Diana Patel",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Photography Paradise",
        user_experience:
          "The Seven Hills offered endless photography opportunities. The landscapes, flora, and fauna were breathtaking.",
        author: "Ethan Roberts",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Delight",
        user_experience:
          "Sampling traditional dishes of the hill communities was delightful. Every meal was rich in flavors and culture.",
        author: "Fiona Gupta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Starlit Nights",
        user_experience:
          "Nights under the clear sky were mesmerizing. Stargazing while sitting around a campfire was a truly magical experience.",
        author: "George Verma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Hilltop Meditation",
        user_experience:
          "Meditating on a quiet hilltop brought immense peace. The serenity and fresh air made it a spiritual experience.",
        author: "Hannah Joshi",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: 5,
    title: "Ladakh Adventures",
    date: "1 July 2024",
    excerpt:
      "We visited Warren on his home trails in Santa Cruz, California, and caught up with what he has been up to lately.",
    img: "/images/manali.jpg",
    link: "#",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Sunrise Trekking",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Alice Johnson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Rafting Fun",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Bob Smith",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Adventure",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Carla Williams",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Camping Under Stars",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "David Lee",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Emma Brown",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Wildlife Spotting",
        user_experience:
          "Saw some rare Himalayan birds. Felt very connected to nature.",
        author: "Frank Garcia",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Bonfire",
        user_experience:
          "The evening bonfire with stories and music was the highlight of the trip.",
        author: "Grace Miller",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Village Visit",
        user_experience:
          "Visiting the local villages gave me insight into traditional life in Manali.",
        author: "Henry Davis",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
];

export const bikes: Bikee[] = [
  {
    id: "serow",
    name: "SEROW",
    logo: "/images/Serow-white.png",
    logoBlack: "/images/serow-black.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 9,
      braking: 7,
      frame: 9,
      tire: 8,
      weight: 9,
      comfort: 7,
    },
    description: [
      "High suspension",
      "Balanced braking power",
      "Lightweight",
      "Strong frame durability",
    ],
  },
  {
    id: "saola",
    name: "SAOLA",
    logo: "/images/Saola-white.png",
    logoBlack: "/images/saola-black.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 7,
      braking: 8,
      frame: 7,
      tire: 6,
      weight: 8,
      comfort: 6,
    },
    description: [
      "Efficient climbing",
      "Responsive braking",
      "Comfortable ride",
      "Good weight balance",
    ],
  },
  {
    id: "takin",
    name: "TAKIN",
    logo: "/images/Takin-white.png",
    logoBlack: "/images/takin-black.png",
    img: "/images/bike-front.png",
    stats: {
      suspension: 8,
      braking: 9,
      frame: 8,
      tire: 7,
      weight: 7,
      comfort: 8,
    },
    description: [
      "Excellent control",
      "Durable build",
      "Powerful braking",
      "All-terrain grip",
    ],
  },
];

export const mockBikes: OverlayBike[] = [
  {
    id: "serow-1",
    name: "SEROW-1",
    logo: "/images/Serow-white.png",
    image: "/images/serow-big-img.png",
    price: "₹10,000",
    skus: [
      { id: "s-1", name: "SEROW-1", image: "/images/serow-big-img.png" },
      { id: "s-2", name: "SEROW-2", image: "/images/serow-big-img.png" },
      { id: "s-3", name: "SEROW-3", image: "/images/serow-big-img.png" },
    ],
    details: {
      size: "M / L",
      color: "Forest Green",
      dimension: "120cm x 40cm x 80cm",
      material: "Alloy Steel",
    },
  },
  {
    id: "saola-1",
    name: "SAOLA-1",
    logo: "/images/Saola-white.png",
    image: "/images/serow-big-img.png",
    price: "₹12,500",
    skus: [
      { id: "s-4", name: "SAOLA-1", image: "/images/serow-big-img.png" },
      { id: "s-5", name: "SAOLA-2", image: "/images/serow-big-img.png" },
      { id: "s-6", name: "SAOLA-3", image: "/images/serow-big-img.png" },
    ],
    details: {
      size: "S / M",
      color: "Sand",
      dimension: "115cm x 38cm x 78cm",
      material: "Carbon Fiber",
    },
  },
  {
    id: "takin-1",
    name: "TAKIN-1",
    logo: "/images/Takin-white.png",
    image: "/images/serow-big-img.png",
    price: "₹9,500",
    skus: [
      { id: "s-7", name: "TAKIN-1", image: "/images/serow-big-img.png" },
      { id: "s-8", name: "TAKIN-2", image: "/images/serow-big-img.png" },
      { id: "s-9", name: "TAKIN-3", image: "/images/serow-big-img.png" },
    ],
    details: {
      size: "M",
      color: "Charcoal",
      dimension: "122cm x 42cm x 82cm",
      material: "Chromoly",
    },
  },
];

export const ourProducts = [
  {
    id: "bikes",
    title: "BIKES",
    image:
      "https://wallpapers.com/images/featured/mountain-bike-nscgkm2azbwgg2py.jpg",
    link: "/bikes",
  },
  {
    id: "apparel",
    title: "APPAREL",
    image: "/images/apparel.png",
    link: "/apparel",
  },
  {
    id: "accessories",
    title: "ACCESSORIES",
    image: "/images/accessories.jpg",
    link: "/accessories",
  },
];

export const steps = [
  {
    title: "Book a Test ride",
    desc: "Choose your preferred cycle model and book a test ride with just a few simple steps.",
    icon: Bike,
  },
  {
    title: "Select a date and timeslot",
    desc: "Pick a convenient date and time that fits your schedule for the test ride.",
    icon: Calendar,
  },
  {
    title: "Rider reaches you",
    desc: "Our expert rider will arrive at your location with the cycle, ready to guide you.",
    icon: Truck,
  },
  {
    title: "Do the test drive",
    desc: "Experience the ride first-hand, explore features, and feel the freedom on wheels.",
    icon: Clock,
  },
];

export const bikesData = [
  {
    name: "Serow",
    logo: "/images/Serow-white.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Internal Cable", value: "Routing" },
      { label: "Mechanical Suspension", value: "Fork" },
      { label: "Mechanical Disc", value: "Brake" },
    ],
    extraFeature: [
      "Smooth internal cable routing",
      "Mechanical suspension fork",
      "Reliable mechanical disc brakes",
    ],
    specs: {
      frameset: "RADFlex Alloy – Internal Cable Routing, 17.5”, Boost – 148MM",
      suspension: "SR Suntour X1 Boost Air, 120MM, Hydraulic Lockout",
      braking: "Shimano MT200 Hydraulic Disc Brakes – 160MM",
    },
    colors: {
      gradient: "#C6B783, #806D2A", // top → bottom
      cta: "var(--color-sandstorm)",
    },
  },
  {
    name: "Saola",
    logo: "/images/Saola-white.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Hydraulic Brake", value: "Disc Brake" },
      { label: "Full Suspension", value: "Suspension" },
      { label: "Carbon Material", value: "Frame" },
    ],
    extraFeature: [
      "Hydraulic disc brakes",
      "Full carbon suspension frame",
      "Lightweight carbon material",
    ],
    specs: {
      frameset: "Carbon Alloy – Internal Cable Routing, 18”",
      suspension: "FOX Float, 130MM, Hydraulic Lockout",
      braking: "Shimano XT Hydraulic Disc Brakes – 180MM",
    },
    colors: {
      gradient: "#0046D7, #FFFFFF",
      cta: "var(--color-airforce)",
    },
  },
  {
    name: "Takin",
    logo: "/images/Takin-white.png",
    image: "/images/bike-curve-view.png",
    features: [
      { label: "Internal Cable", value: "Routing" },
      { label: "Mechanical Suspension", value: "Fork" },
      { label: "Mechanical Disc", value: "Brake" },
    ],
    extraFeature: [
      "Internal cable routing",
      "Mechanical suspension fork",
      "Mechanical disc brakes",
    ],
    specs: {
      frameset: "Aluminum Alloy – Internal Cable Routing, 17”",
      suspension: "RockShox Judy, 120MM, Hydraulic Lockout",
      braking: "Shimano MT400 Hydraulic Disc Brakes – 160MM",
    },
    colors: {
      gradient: "#516316, #F1FFC3",
      cta: "var(--color-army)",
    },
  },
];

export const stores: Store[] = [
  {
    id: 1,
    name: "Store Mumbai 1",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    address: "Andheri West",
  },
  {
    id: 2,
    name: "Store Mumbai 2",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.1,
    lng: 72.88,
    address: "Bandra",
  },
  {
    id: 3,
    name: "Store Mumbai 3",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.09,
    lng: 72.87,
    address: "Juhu",
  },
  {
    id: 4,
    name: "Store Pune 1",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    address: "Koregaon Park",
  },
  {
    id: 5,
    name: "Store Pune 2",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.53,
    lng: 73.85,
    address: "Viman Nagar",
  },
  {
    id: 6,
    name: "Store Delhi 1",
    city: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    address: "Connaught Place",
  },
  {
    id: 7,
    name: "Store Delhi 2",
    city: "Delhi",
    state: "Delhi",
    lat: 28.61,
    lng: 77.21,
    address: "Karol Bagh",
  },
  {
    id: 8,
    name: "Store Delhi 3",
    city: "Delhi",
    state: "Delhi",
    lat: 28.63,
    lng: 77.22,
    address: "Saket",
  },
  {
    id: 9,
    name: "Store Bangalore 1",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    address: "MG Road",
  },
  {
    id: 10,
    name: "Store Bangalore 2",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.97,
    lng: 77.59,
    address: "Koramangala",
  },
  {
    id: 11,
    name: "Store Bangalore 3",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.98,
    lng: 77.6,
    address: "Indiranagar",
  },
  {
    id: 12,
    name: "Store Hyderabad 1",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lng: 78.4867,
    address: "Banjara Hills",
  },
  {
    id: 13,
    name: "Store Hyderabad 2",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.39,
    lng: 78.48,
    address: "Hitech City",
  },
  {
    id: 14,
    name: "Store Hyderabad 3",
    city: "Hyderabad",
    state: "Telangana",
    lat: 17.38,
    lng: 78.48,
    address: "Gachibowli",
  },
  {
    id: 15,
    name: "Store Chennai 1",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    address: "T. Nagar",
  },
  {
    id: 16,
    name: "Store Chennai 2",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    address: "Adyar",
  },
  {
    id: 17,
    name: "Store Chennai 3",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.09,
    lng: 80.26,
    address: "Velachery",
  },
  {
    id: 18,
    name: "Store Kolkata 1",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.5726,
    lng: 88.3639,
    address: "Salt Lake",
  },
  {
    id: 19,
    name: "Store Kolkata 2",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.36,
    address: "Park Street",
  },
  {
    id: 20,
    name: "Store Kolkata 3",
    city: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.37,
    address: "New Town",
  },
  {
    id: 21,
    name: "Store Jaipur 1",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    address: "MI Road",
  },
  {
    id: 22,
    name: "Store Jaipur 2",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.78,
    address: "C-Scheme",
  },
  {
    id: 23,
    name: "Store Jaipur 3",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.79,
    address: "Bani Park",
  },
  {
    id: 24,
    name: "Store Lucknow 1",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.8467,
    lng: 80.9462,
    address: "Gomti Nagar",
  },
  {
    id: 25,
    name: "Store Lucknow 2",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.85,
    lng: 80.95,
    address: "Hazratganj",
  },
  {
    id: 26,
    name: "Store Lucknow 3",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.84,
    lng: 80.94,
    address: "Alambagh",
  },
  {
    id: 27,
    name: "Store Ahmedabad 1",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    address: "CG Road",
  },
  {
    id: 28,
    name: "Store Ahmedabad 2",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.02,
    lng: 72.57,
    address: "Navrangpura",
  },
  {
    id: 29,
    name: "Store Ahmedabad 3",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.03,
    lng: 72.58,
    address: "Satellite",
  },
  {
    id: 30,
    name: "Store Kochi 1",
    city: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    address: "MG Road",
  },
  {
    id: 31,
    name: "Store Kochi 2",
    city: "Kochi",
    state: "Kerala",
    lat: 9.93,
    lng: 76.27,
    address: "Marine Drive",
  },
  {
    id: 32,
    name: "Store Kochi 3",
    city: "Kochi",
    state: "Kerala",
    lat: 9.94,
    lng: 76.26,
    address: "Vyttila",
  },
  {
    id: 33,
    name: "Store Surat 1",
    city: "Surat",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
    address: "Varachha",
  },
  {
    id: 34,
    name: "Store Surat 2",
    city: "Surat",
    state: "Gujarat",
    lat: 21.17,
    lng: 72.83,
    address: "Adajan",
  },
  {
    id: 35,
    name: "Store Surat 3",
    city: "Surat",
    state: "Gujarat",
    lat: 21.16,
    lng: 72.83,
    address: "Pal",
  },
  {
    id: 36,
    name: "Store Indore 1",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.7196,
    lng: 75.8577,
    address: "MG Road",
  },
  {
    id: 37,
    name: "Store Indore 2",
    city: "Indore",
    state: "Madhya Pradesh",
    lat: 22.72,
    lng: 75.85,
    address: "Vijay Nagar",
  },
  {
    id: 38,
    name: "Store Patna 1",
    city: "Patna",
    state: "Bihar",
    lat: 25.5941,
    lng: 85.1376,
    address: "Boring Road",
  },
  {
    id: 39,
    name: "Store Patna 2",
    city: "Patna",
    state: "Bihar",
    lat: 25.59,
    lng: 85.13,
    address: "Kankarbagh",
  },
  {
    id: 40,
    name: "Store Guwahati 1",
    city: "Guwahati",
    state: "Assam",
    lat: 26.1445,
    lng: 91.7362,
    address: "Pan Bazaar",
  },
  {
    id: 41,
    name: "Store Guwahati 2",
    city: "Guwahati",
    state: "Assam",
    lat: 26.14,
    lng: 91.73,
    address: "Paltan Bazaar",
  },
  {
    id: 42,
    name: "Store Bhopal 1",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    address: "MP Nagar",
  },
  {
    id: 43,
    name: "Store Bhopal 2",
    city: "Bhopal",
    state: "Madhya Pradesh",
    lat: 23.26,
    lng: 77.41,
    address: "Kolar Road",
  },
  {
    id: 44,
    name: "Store Trivandrum 1",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    address: "MG Road",
  },
  {
    id: 45,
    name: "Store Trivandrum 2",
    city: "Trivandrum",
    state: "Kerala",
    lat: 8.52,
    lng: 76.93,
    address: "Vazhuthacaud",
  },
  {
    id: 46,
    name: "Store Ranchi 1",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.3441,
    lng: 85.3096,
    address: "Harmu Road",
  },
  {
    id: 47,
    name: "Store Ranchi 2",
    city: "Ranchi",
    state: "Jharkhand",
    lat: 23.34,
    lng: 85.3,
    address: "Kantatoli",
  },
  {
    id: 48,
    name: "Store Vadodara 1",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3072,
    lng: 73.1812,
    address: "Alkapuri",
  },
  {
    id: 49,
    name: "Store Vadodara 2",
    city: "Vadodara",
    state: "Gujarat",
    lat: 22.3,
    lng: 73.18,
    address: "Manjalpur",
  },
  {
    id: 50,
    name: "Store Nashik 1",
    city: "Nashik",
    state: "Maharashtra",
    lat: 19.9975,
    lng: 73.7898,
    address: "College Road",
  },
];
