import { Destination } from "@/types/destination";

export const destinations: Destination[] = [
  {
    id: "1",
    title: "MANALI",
    subtitle: "Remarkable experience to inspire the mind",
    date: "20 September 2025",
    seat: "3 seats left",
    excerpt:
      "We visited Warren on his home trails in Santa Cruz, California, and caught up with what he has been up to lately.",
    description: `Glacial Lakes ; High Passes ; Snowy Peaks ; Green Rivers; Vast Plains ; Temperate Forests ; Cold Deserts ; a culture preserved for centuries! This is the heart of the Himalaya! Manali-Leh is a highly popular cycling jaunt, frequented by cyclists from across the world.`,
    leftImage: "/images/manali-img.jpg",
    mapImage: "/images/tour-map.png",
    contourImage: "/images/contour.png",
    link: "/stories/1/manali",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
    source: { lat: 28.6139, lng: 77.209 },
    destination: { lat: 32.2396, lng: 77.1887 },
    reviews: [
      { category: "Scenery & Views", rating: 5, max: 5 },
      { category: "Adventure Activities", rating: 5, max: 5 },
      { category: "Hospitality & Stay", rating: 4, max: 5 },
      { category: "Food & Local Cuisine", rating: 3, max: 5 },
      { category: "Travel Convenience", rating: 3, max: 5 },
    ],
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Sunrise Trekking",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Alice Johnson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Rafting Fun",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Bob Smith",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Adventure",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Carla Williams",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Camping Under Stars",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "David Lee",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Emma Brown",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Wildlife Spotting",
        user_experience:
          "Saw some rare Himalayan birds. Felt very connected to nature.",
        author: "Frank Garcia",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Bonfire",
        user_experience:
          "The evening bonfire with stories and music was the highlight of the trip.",
        author: "Grace Miller",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Village Visit",
        user_experience:
          "Visiting the local villages gave me insight into traditional life in Manali.",
        author: "Henry Davis",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: "spiti-valley",
    title: "SpiTI VALLEY",
    subtitle: "Remarkable experience to inspire the mind",
    date: "23 December 2023",
    urgent:"Registrations Open",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    description: `Glacial Lakes ; High Passes ; Snowy Peaks ; Green Rivers; Vast Plains ; Temperate Forests ; Cold Deserts ; a culture preserved for centuries! This is the heart of the Himalaya! Manali-Leh is a highly popular cycling jaunt, frequented by cyclists from across the world.`,
    leftImage: "/images/spiti-img.jpg",
    mapImage: "/images/tour-map.png",
    link: "/stories/2/spiti-valley",
    className: "absolute top-25 left-[25%] rotate-[-7deg]",
    contourImage: "/images/contour.png",
    source: { lat: 25.3176, lng: 82.9739 },
    destination: { lat: 34.1526, lng: 77.577 },
    reviews: [
      { category: "Scenery & Views", rating: 5, max: 5 },
      { category: "Adventure Activities", rating: 5, max: 5 },
      { category: "Hospitality & Stay", rating: 4, max: 5 },
      { category: "Food & Local Cuisine", rating: 3, max: 5 },
      { category: "Travel Convenience", rating: 3, max: 5 },
    ],
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Chai Plantation Walk",
        user_experience:
          "Walking through the tea plantations was serene and calming. The aroma of fresh chai leaves made the whole experience magical.",
        author: "Irene Thomas",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Sunset Viewpoint",
        user_experience:
          "The sunset over Spiti valley is something I will never forget. Colors of the sky reflected on the river created a painting-like scene.",
        author: "Jack Wilson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Homestay Experience",
        user_experience:
          "Staying at a local homestay made me feel at home. The hosts shared their culture and traditional meals with so much warmth.",
        author: "Karen Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "Every corner of Spiti is photogenic! The rugged mountains, winding rivers, and colorful monasteries were perfect for photography.",
        author: "Leo Martinez",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Monastery Visit",
        user_experience:
          "Visiting ancient monasteries gave me a deep insight into local spirituality. The monks were welcoming and explained their rituals patiently.",
        author: "Maya Patel",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Village Interaction",
        user_experience:
          "Talking to the villagers was enlightening. I learned how they cultivate crops in such harsh conditions and their love for community.",
        author: "Nikhil Rao",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Side Chai Break",
        user_experience:
          "Sipping fresh chai beside the river while listening to the flowing water was the most peaceful experience I’ve had in years.",
        author: "Olivia Chen",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Stargazing Night",
        user_experience:
          "The night sky in Spiti is unbelievably clear. Stargazing with a cup of chai made me feel connected to the universe.",
        author: "Pranav Desai",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: "chai-plantation-walk",
    title: "Chai Plantation Walk",
    subtitle: "Remarkable experience to inspire the mind",
    date: "23 December 2023",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    description: `Glacial Lakes ; High Passes ; Snowy Peaks ; Green Rivers; Vast Plains ; Temperate Forests ; Cold Deserts ; a culture preserved for centuries! This is the heart of the Himalaya! Manali-Leh is a highly popular cycling jaunt, frequented by cyclists from across the world.`,
    leftImage: "/images/spiti-valley.jpg",
    mapImage: "/images/tour-map.png",
    link: "/stories/3/chai-plantation-walk",
    className: "absolute top-25 left-[25%] rotate-[-7deg]",
    contourImage: "/images/contour.png",
    source: { lat: 25.3176, lng: 82.9739 },
    destination: { lat: 34.1526, lng: 77.577 },
    reviews: [
      { category: "Scenery & Views", rating: 5, max: 5 },
      { category: "Adventure Activities", rating: 5, max: 5 },
      { category: "Hospitality & Stay", rating: 4, max: 5 },
      { category: "Food & Local Cuisine", rating: 3, max: 5 },
      { category: "Travel Convenience", rating: 3, max: 5 },
    ],
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Spiritual Awakening",
        user_experience:
          "Visiting Kali’s Abode felt like a spiritual awakening. The atmosphere is serene and charged with positive energy.",
        author: "Sarah Thompson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Temple Architecture",
        user_experience:
          "The intricate carvings and traditional architecture of the temple left me awestruck. Every detail tells a story.",
        author: "Ravi Kumar",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Meditation Sessions",
        user_experience:
          "Participating in meditation sessions here gave me peace like never before. The guides were knowledgeable and patient.",
        author: "Anita Joshi",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Rituals",
        user_experience:
          "Observing the local rituals was fascinating. I learned so much about Faridkots’ traditions and cultural heritage.",
        author: "Manish Verma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Scenic Trails",
        user_experience:
          "The trails around Kali’s Abode are scenic and peaceful. Every walk felt like a journey into nature’s heart.",
        author: "Priya Sharma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Community Interaction",
        user_experience:
          "Interacting with the local community enriched my experience. Their stories and hospitality were heartwarming.",
        author: "Rahul Mehta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Aarti",
        user_experience:
          "The evening aarti was mesmerizing. The chants, lamps, and devotion created a magical ambiance.",
        author: "Neha Gupta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Nature Walks",
        user_experience:
          "Walking through the surrounding forests and hills was refreshing. The connection with nature was revitalizing.",
        author: "Vikram Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: "kali-abode",
    title: "Kali's Abode, Faridkots Reverence",
    subtitle: "Remarkable experience to inspire the mind",
    date: "23 December 2023",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    description: `Glacial Lakes ; High Passes ; Snowy Peaks ; Green Rivers; Vast Plains ; Temperate Forests ; Cold Deserts ; a culture preserved for centuries! This is the heart of the Himalaya! Manali-Leh is a highly popular cycling jaunt, frequented by cyclists from across the world.`,
    leftImage: "/images/kali-img.jpg",
    mapImage: "/images/tour-map.png",
    link: "/stories/4/kali-abode",
    className: "absolute top-5 left-[40%] rotate-[8deg]",
    contourImage: "/images/contour.png",
    source: { lat: 25.3176, lng: 82.9739 },
    destination: { lat: 34.1526, lng: 77.577 },
    reviews: [
      { category: "Scenery & Views", rating: 5, max: 5 },
      { category: "Adventure Activities", rating: 5, max: 5 },
      { category: "Hospitality & Stay", rating: 4, max: 5 },
      { category: "Food & Local Cuisine", rating: 3, max: 5 },
      { category: "Travel Convenience", rating: 3, max: 5 },
    ],
     images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Hilltop Sunrise",
        user_experience:
          "Waking up on the hilltops to witness the sunrise was an unforgettable experience. The sky was painted in vivid colors.",
        author: "Alex Turner",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Forest Trekking",
        user_experience:
          "Trekking through dense forests around the hills brought me close to nature. Birds and wildlife sightings made it magical.",
        author: "Bella Martin",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Village Exploration",
        user_experience:
          "Exploring local villages gave me insight into rural life and traditions. The hospitality of villagers was heartwarming.",
        author: "Charlie Singh",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Waterfall Adventure",
        user_experience:
          "Discovering hidden waterfalls along the trails was thrilling. The cool water and scenic surroundings were perfect for relaxation.",
        author: "Diana Patel",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Photography Paradise",
        user_experience:
          "The Seven Hills offered endless photography opportunities. The landscapes, flora, and fauna were breathtaking.",
        author: "Ethan Roberts",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Delight",
        user_experience:
          "Sampling traditional dishes of the hill communities was delightful. Every meal was rich in flavors and culture.",
        author: "Fiona Gupta",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Starlit Nights",
        user_experience:
          "Nights under the clear sky were mesmerizing. Stargazing while sitting around a campfire was a truly magical experience.",
        author: "George Verma",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Hilltop Meditation",
        user_experience:
          "Meditating on a quiet hilltop brought immense peace. The serenity and fresh air made it a spiritual experience.",
        author: "Hannah Joshi",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
  {
    id: "the-seven-hills",
    title: "The Seven Hills",
    subtitle: "Remarkable experience to inspire the mind",
    date: "15 August 2020",
    excerpt:
      "Wilson has been bringing the International Yeti Gatherings to life for ten years through H+I Adventures, a tour outfit co-founded by Wilson in 2007.",
    description: `Glacial Lakes ; High Passes ; Snowy Peaks ; Green Rivers; Vast Plains ; Temperate Forests ; Cold Deserts ; a culture preserved for centuries! This is the heart of the Himalaya! Manali-Leh is a highly popular cycling jaunt, frequented by cyclists from across the world.`,
    leftImage: "/images/spiti-valley.jpg",
    mapImage: "/images/tour-map.png",
    link: "/stories/5/the-seven-hills",
    className: "absolute top-20 left-[8%] rotate-[-5deg]",
    contourImage: "/images/contour.png",
    source: { lat: 25.3176, lng: 82.9739 },
    destination: { lat: 34.1526, lng: 77.577 },
    reviews: [
      { category: "Scenery & Views", rating: 5, max: 5 },
      { category: "Adventure Activities", rating: 5, max: 5 },
      { category: "Hospitality & Stay", rating: 4, max: 5 },
      { category: "Food & Local Cuisine", rating: 3, max: 5 },
      { category: "Travel Convenience", rating: 3, max: 5 },
    ],
    images: [
      "/images/manali/manali1.jpg",
      "/images/manali/manali2.jpeg",
      "/images/manali/manali3.jpeg",
      "/images/manali/manali4.jpg",
      "/images/manali/manali5.jpg",
      "/images/manali/manali6.jpg",
      "/images/manali/manali7.jpeg",
      "/images/manali/manali8.jpeg",
      "/images/manali/manali9.jpg",
      "/images/manali/manali10.jpg",
      "/images/manali/manali11.jpg",
      "/images/manali/manali12.jpeg",
      "/images/manali/manali13.webp",
      "/images/manali/manali14.jpeg",
      "/images/manali/manali15.jpg",
      "/images/manali/manali16.jpeg",
      "/images/manali/manali17.webp",
      "/images/manali/manali18.webp",
      "/images/manali/manali19.jpeg",
      "/images/manali/manali20.webp",
    ],
    content: [
      {
        title: "Sunrise Trekking",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Alice Johnson",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "River Rafting Fun",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Bob Smith",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Cuisine Adventure",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Carla Williams",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Camping Under Stars",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "David Lee",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Mountain Photography",
        user_experience:
          "The sunrise trek was an experience that will forever remain etched in my memory. As I began the hike in the early hours, the air was crisp and carried the subtle scent of pine and earth, awakening every sense within me. Each step along the winding trail brought me closer to a vantage point that promised a view unlike any I had ever seen. The soft glow of dawn started to illuminate the horizon, and the first hints of sunlight painted the rugged mountain peaks in shades of gold and amber, casting long shadows across the valleys below. It was a surreal moment where nature itself seemed to pause and hold its breath, welcoming the day with quiet grandeur. As I climbed higher, the tranquility of the morning enveloped me. The gentle rustling of leaves, the distant call of birds, and the faint murmur of a nearby stream created a symphony that was both soothing and invigorating. Each step was a reminder of the effort it took to reach this place, yet the anticipation of the unfolding panorama kept my spirits buoyant. When I finally reached the summit, I was greeted by a breathtaking spectacle: the sun, gradually climbing over the horizon, cast a warm, golden light that danced on the mountain slopes. The sky transformed into a canvas of vibrant hues—fiery oranges blending into soft pinks, delicate purples fading into deep blues. The mountains themselves seemed to glow with a life of their own, their rugged contours accentuated by the interplay of light and shadow. Standing there, with the cool breeze brushing against my face and the vast expanse of nature stretching endlessly before me, I felt an overwhelming sense of serenity and exhilaration.",
        author: "Emma Brown",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Wildlife Spotting",
        user_experience:
          "Saw some rare Himalayan birds. Felt very connected to nature.",
        author: "Frank Garcia",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Evening Bonfire",
        user_experience:
          "The evening bonfire with stories and music was the highlight of the trip.",
        author: "Grace Miller",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
      {
        title: "Local Village Visit",
        user_experience:
          "Visiting the local villages gave me insight into traditional life in Manali.",
        author: "Henry Davis",
        date: "21 September 2025",
        author_img: "/images/manali/rider-img.jpg",
      },
    ],
  },
];